mixt_model <- function(m, S, P, N, sed) {

	##########################################################################
	# FUNCTION
	#   [X,y]=mixt_model(m,S,P,N,sed)
	#
	# Generates a set of data vectors that stem from a mixture of normal 
	# distributions (also used in Chapter 2).
	#
	# INPUT ARGUMENTS:
	#   m:  lxc matrix whose i-th column contains the
	#       (l-dimensional) mean of the i-th normal distribution.
	#   S:  lxlxc matrix whose i-th lxl two-dimensional "slice" is the
	#       covariance matrix corresponding to the i-th normal distribution.
	#   P:  c-dimensional vector whose i-th coordinate contains
	#       the a priori probability for the i-th normal  distribution.
	#   N:  the total number of points to be generated by the mixture
	#       distribution.
	#   sed:  the seed used for the initialization of the built-in MATLAB
	#         random generator function "rand".
	#
	# OUTPUT ARGUMENTS:
	#   X:  lxN matrix whose columns are the produced vectors.
	#   y:  N-dimensional vector whose i-th element indicates the
	#       distribution generated the i-th vector.
	#
	# (c) 2010 S. Theodoridis, A. Pikrakis, K. Koutroumbas, D. Cavouras
	#
	# Converted from Matlab into R by S.D. Separa (2015)
	#
	##########################################################################
	
	require(MASS)
	
	set.seed(sed)
	
	size = dim(m)
	
	l = size[1]
	c_ = size[2]
	
	P_acc = P[1]

	# Constructing the P_acc vector. This is necessary for picking randomly
	# one of the c normal distributions in order to generate a point.
	for (i in 2:c_) {
		t = P_acc[i-1]+P[i]
		P_acc = c(P_acc, t)
	}
	
	# Generation of the data set
	X = numeric(0)
	y = numeric(0)
	
	for (i in 1:N) {
		t = runif(1)
		ind = sum(t>P_acc)+1  # Index of the normal distribution that will generate the i-th vector
		X = cbind(X, as.matrix(mvrnorm(n=1, mu = m[, ind], Sigma = S[,,ind])))
		y <- c(y, ind)
	}
	
	return(list("X" = t(X), "y" = y))
}
